"""
annotator.py — Crop and annotate screenshots using Pillow.

Coordinates from Kimi are fractions [0.0…1.0] of the ORIGINAL image.
Annotation rectangles are expressed in the same original coordinate space;
the pipeline adjusts them to the cropped image when drawing.
"""
from pathlib import Path

from PIL import Image, ImageDraw

ANNOTATION_COLOR = "#FF3333"   # red, matching image_annotator.py
ANNOTATION_WIDTH = 3           # line thickness in pixels


def process_image(src: Path, item: dict, dst: Path) -> None:
    """
    Load *src*, apply crop + red-rectangle annotations from *item*, save to *dst*.

    item dict keys (all generated by vision.py / Kimi):
        "crop"         : [left, top, right, bottom] as 0-1 fractions, or None
        "annotations"  : list of [left, top, right, bottom] (original fractions)
        (other keys are ignored here)
    """
    dst.parent.mkdir(parents=True, exist_ok=True)

    img = Image.open(src).convert("RGB")
    W, H = img.size

    crop = item.get("crop")
    annotations = item.get("annotations") or []

    # Convert annotation fractions to original-image pixels
    ann_orig_px: list[tuple[int, int, int, int]] = []
    for ann in annotations:
        if isinstance(ann, (list, tuple)) and len(ann) == 4:
            ax1 = int(_clamp(ann[0]) * W)
            ay1 = int(_clamp(ann[1]) * H)
            ax2 = int(_clamp(ann[2]) * W)
            ay2 = int(_clamp(ann[3]) * H)
            if ax2 > ax1 and ay2 > ay1:
                ann_orig_px.append((ax1, ay1, ax2, ay2))

    # Crop
    crop_ox, crop_oy = 0, 0
    if crop and isinstance(crop, (list, tuple)) and len(crop) == 4:
        cx1 = max(0, int(_clamp(crop[0]) * W))
        cy1 = max(0, int(_clamp(crop[1]) * H))
        cx2 = min(W, int(_clamp(crop[2]) * W))
        cy2 = min(H, int(_clamp(crop[3]) * H))
        if cx2 > cx1 and cy2 > cy1:
            img = img.crop((cx1, cy1, cx2, cy2))
            crop_ox, crop_oy = cx1, cy1

    # Draw annotations (shifted into cropped coordinate space)
    if ann_orig_px:
        draw = ImageDraw.Draw(img)
        for ax1, ay1, ax2, ay2 in ann_orig_px:
            rx1 = ax1 - crop_ox
            ry1 = ay1 - crop_oy
            rx2 = ax2 - crop_ox
            ry2 = ay2 - crop_oy
            draw.rectangle([rx1, ry1, rx2, ry2],
                           outline=ANNOTATION_COLOR,
                           width=ANNOTATION_WIDTH)

    img.save(dst, format="PNG")


def _clamp(v) -> float:
    """Clamp a value to [0.0, 1.0]."""
    try:
        return max(0.0, min(1.0, float(v)))
    except (TypeError, ValueError):
        return 0.0
