"""
annotator.py — Crop and annotate screenshots using Pillow.

Crop coordinates from vision.py are fractions [0.0…1.0] of the original image.
Annotation rectangles are pixel integers in the CROPPED image's coordinate space.
"""
from pathlib import Path

from PIL import Image

from .bounding_box import draw_annotations, ANNOTATION_COLOR, ANNOTATION_WIDTH


def process_image(src: Path, item: dict, dst: Path) -> None:
    """
    Load *src*, apply crop + red-rectangle annotations from *item*, save to *dst*.

    item dict keys (all generated by vision.py / Kimi):
        "crop"         : [left, top, right, bottom] as 0-1 fractions, or None
        "annotations"  : list of [left, top, right, bottom] in pixel coords
                         relative to the cropped image
        (other keys are ignored here)
    """
    dst.parent.mkdir(parents=True, exist_ok=True)

    img = Image.open(src).convert("RGB")
    W, H = img.size

    crop = item.get("crop")
    annotations = item.get("annotations") or []

    # Crop
    if crop and isinstance(crop, (list, tuple)) and len(crop) == 4:
        cx1 = max(0, int(_clamp(crop[0]) * W))
        cy1 = max(0, int(_clamp(crop[1]) * H))
        cx2 = min(W, int(_clamp(crop[2]) * W))
        cy2 = min(H, int(_clamp(crop[3]) * H))
        if cx2 > cx1 and cy2 > cy1:
            img = img.crop((cx1, cy1, cx2, cy2))

    # Draw annotations using bounding_box.draw_annotations() for consistency
    if annotations:
        img = draw_annotations(img, annotations)

    img.save(dst, format="PNG")


def _clamp(v) -> float:
    """Clamp a value to [0.0, 1.0]."""
    try:
        return max(0.0, min(1.0, float(v)))
    except (TypeError, ValueError):
        return 0.0
