"""
latex_gen.py — Generate a complete LaTeX lab report from structured analysis data.

The output is a full standalone .tex file that matches the main.tex gold
standard format (same macros, same preamble, same grayscale theme).
"""
from __future__ import annotations


# ---------------------------------------------------------------------------
# LaTeX preamble — identical to the gold-standard main.tex
# ---------------------------------------------------------------------------
_PREAMBLE = r"""% ============================================================
%  LAB REPORT — generated by labber
%  Compile with:  pdflatex main_generated.tex
% ============================================================

\documentclass[12pt, a4paper]{report}

% ── Encoding & Language ──────────────────────────────────────
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}

% ── Modern Typeface ──────────────────────────────────────────
\usepackage{sourcesans}
\usepackage{sourceserif}
\renewcommand{\familydefault}{\sfdefault}

% ── Page Geometry ────────────────────────────────────────────
\usepackage[
  top=2.5cm, bottom=2.5cm,
  left=2.8cm, right=2.8cm,
  headheight=14pt
]{geometry}

% ── Color (grayscale palette) ────────────────────────────────
\usepackage{xcolor}
\definecolor{ink}{gray}{0.08}
\definecolor{accent}{gray}{0.22}
\definecolor{mid}{gray}{0.48}
\definecolor{light}{gray}{0.88}
\definecolor{verylightgray}{gray}{0.95}

% ── Typography & Spacing ─────────────────────────────────────
\usepackage{microtype}
\usepackage{setspace}
\setstretch{1.25}
\usepackage{parskip}
\setlength{\parindent}{0pt}

% ── Headers & Footers ────────────────────────────────────────
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhf{}
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\headrule}{\hbox to\headwidth{\color{light}\leaders\hrule height \headrulewidth\hfill}}
\fancyhead[L]{\color{mid}\small\textit{Lab \labnum\ --- \labtitle}}
\fancyhead[R]{\color{mid}\small\coursecode}
\fancyfoot[C]{\color{mid}\small\thepage}

% ── Section Styling ──────────────────────────────────────────
\usepackage{titlesec}

\titleformat{\chapter}[display]
  {\color{accent}\sffamily\Large\bfseries}
  {}
  {0pt}
  {\huge}
\titlespacing*{\chapter}{0pt}{-30pt}{12pt}

\titleformat{\section}
  {\color{accent}\sffamily\large\bfseries}
  {}
  {0pt}
  {}
\titlespacing*{\section}{0pt}{18pt}{6pt}

\titleformat{\subsection}
  {\color{accent}\sffamily\normalsize\bfseries}
  {}
  {0pt}
  {}
\titlespacing*{\subsection}{0pt}{12pt}{4pt}

% ── Table of Contents ────────────────────────────────────────
\usepackage{titletoc}
\usepackage{tocloft}
\renewcommand{\cftchapfont}{\sffamily\bfseries\color{accent}}
\renewcommand{\cftsecfont}{\sffamily\color{ink}}
\renewcommand{\cftchapleader}{\color{light}\cftdotfill{\cftdotsep}}
\renewcommand{\cftsecleader}{\color{light}\cftdotfill{\cftdotsep}}
\renewcommand{\cftchappagefont}{\sffamily\bfseries\color{accent}}
\renewcommand{\cftsecpagefont}{\sffamily\color{mid}}
\setlength{\cftbeforechapskip}{6pt}

% ── Figures & Captions ───────────────────────────────────────
\usepackage{graphicx}
\usepackage{float}
\usepackage[
  labelfont={bf, color=accent},
  textfont={color=mid},
  font=small,
  justification=centering,
  skip=6pt
]{caption}

\usepackage{mdframed}
\mdfdefinestyle{figbox}{
  linecolor=ink,
  linewidth=0.4pt,
  innertopmargin=2pt,
  innerbottommargin=2pt,
  innerrightmargin=0pt,
  innerleftmargin=0pt,
  backgroundcolor=white,
  roundcorner=0pt
}

\mdfdefinestyle{answerbox}{
  linecolor=accent,
  linewidth=1.2pt,
  innertopmargin=8pt,
  innerbottommargin=8pt,
  innerrightmargin=10pt,
  innerleftmargin=10pt,
  backgroundcolor=verylightgray,
  roundcorner=4pt
}

% ── Hyperlinks ───────────────────────────────────────────────
\usepackage[
  colorlinks=true,
  linkcolor=accent,
  urlcolor=accent,
  citecolor=mid,
  pdftitle={Lab Report},
  pdfauthor={Team}
]{hyperref}

% ── Misc ─────────────────────────────────────────────────────
\usepackage{booktabs}
\usepackage{enumitem}
\setlist[itemize]{leftmargin=*, itemsep=2pt, topsep=4pt}

% ── Custom Commands ──────────────────────────────────────────

\newcommand{\ans}[1]{\textbf{\color{accent}#1}}

\newcounter{modnum}
\newcommand{\module}[1]{%
  \stepcounter{modnum}%
  \setcounter{qnum}{0}%
  \chapter*{Module \arabic{modnum}: #1}%
  \addcontentsline{toc}{chapter}{Module \arabic{modnum}: #1}%
}

\newcounter{qnum}
\newcommand{\question}[1]{%
  \stepcounter{qnum}%
  \section*{Q\arabic{modnum}.\arabic{qnum})\quad #1}%
  \addcontentsline{toc}{section}{Q\arabic{modnum}.\arabic{qnum}: #1}%
}

\newcommand{\screenshot}[3][\linewidth]{%
  \begin{figure}[H]
    \centering
    \begin{mdframed}[style=figbox]
      \centering
      \includegraphics[width=\dimexpr#1-4pt\relax]{#2}
    \end{mdframed}
    \caption{#3}
  \end{figure}%
}

\newcommand{\ansbox}[1]{%
    \vspace{8pt}%
    \begin{mdframed}[style=answerbox]
        \textbf{Answer:}\quad #1
    \end{mdframed}%
}

% ── Lab Metadata ─────────────────────────────────────────────
\newcommand{\coursename}{Digital Forensics}
\newcommand{\coursecode}{CBE322}
\newcommand{\labnum}{5}
\newcommand{\labtitle}{Magnet AXIOM: OS, Encryption and Credentials}
\newcommand{\labdate}{March 22, 2026}

\newcommand{\teamtable}{%
  \begin{tabular}{ll}
    Kandarp Jindal          & 2023BCY0044 \\
    Akshat Ajit Saraswat    & 2023BCY0048 \\
  \end{tabular}%
}

\setcounter{modnum}{2}
"""

_TITLEPAGE = r"""
\begin{document}

% ── Title Page ───────────────────────────────────────────────
\begin{titlepage}
  \thispagestyle{empty}
  \pagecolor{white}

  {\color{accent}\rule{\linewidth}{2.5pt}}
  \vspace{0.5em}

  {\color{mid}\sffamily\large
    \textbf{\coursename} \hfill \textbf{\coursecode}
  }

  \vspace{0.3em}
  {\color{light}\rule{\linewidth}{0.8pt}}

  \vspace{3.5cm}

  \begin{center}
    {\color{accent}\sffamily\fontsize{11}{13}\selectfont
      \textls[120]{LAB \labnum}}\\[6pt]
    {\color{ink}\sffamily\fontsize{26}{32}\selectfont\bfseries \labtitle}
  \end{center}

  \vspace{3cm}

  \begin{center}
    {\color{mid}\sffamily\large \labdate}
  \end{center}

  \vspace{2.5cm}

  \begin{center}
    {\large \teamtable}
  \end{center}

  \vfill

  {\color{light}\rule{\linewidth}{0.8pt}}
  \vspace{0.4em}
  {\color{accent}\rule{\linewidth}{2.5pt}}
\end{titlepage}

% ── Table of Contents ────────────────────────────────────────
\newpage
\thispagestyle{empty}

\vspace*{1cm}
{\color{accent}\sffamily\Huge\bfseries Index}\\[4pt]
{\color{accent}\rule{\linewidth}{2pt}}
\vspace{1cm}

{
  \setstretch{1.5}
  \tableofcontents
}
\thispagestyle{empty}

\newpage
\setcounter{page}{1}
\pagestyle{fancy}

% ── Report Content ───────────────────────────────────────────
"""

_END = r"""
\end{document}
"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Characters that must be escaped when they appear in raw (non-LaTeX) text
# passed to \question{} — Kimi's explanation/answer_latex is trusted to
# already be LaTeX-safe.
_ESCAPE_MAP = str.maketrans(
    {
        "&": r"\&",
        "%": r"\%",
        "#": r"\#",
        "_": r"\_",
        "$": r"\$",
        "^": r"\^{}",
        "~": r"\~{}",
    }
)


def _esc(text: str) -> str:
    """Escape LaTeX special characters in plain text (not pre-written LaTeX)."""
    return text.translate(_ESCAPE_MAP)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def render_question(
    module_num: int,
    q_num: int,
    q_text: str,
    analysis: dict,
    images_dir: str = "lab5img",
) -> str:
    """Return LaTeX source for one question block."""
    lines: list[str] = []

    lines.append(f"\\question{{{_esc(q_text)}}}")
    lines.append("")

    explanation = (analysis.get("explanation") or "").strip()
    if explanation:
        lines.append(explanation)
        lines.append("")

    for img_item in analysis.get("images") or []:
        output_name = (img_item.get("output_name") or "").strip()
        caption = _esc(img_item.get("caption") or "")
        if output_name:
            lines.append(f"\\screenshot{{{images_dir}/{output_name}}}{{{caption}}}")
            lines.append("")

    answer_latex = (analysis.get("answer_latex") or "").strip()
    if answer_latex:
        lines.append(f"\\ansbox{{{answer_latex}}}")
        lines.append("")

    return "\n".join(lines)


def render_module(
    module_title: str,
    questions_analyses: list[tuple[int, str, dict]],
    images_dir: str = "lab5img",
) -> str:
    """
    Return LaTeX source for one full module.

    questions_analyses: list of (q_num, q_text, analysis_dict)
    """
    parts: list[str] = [f"\\module{{{_esc(module_title)}}}", ""]

    for q_num, q_text, analysis in questions_analyses:
        parts.append(render_question(
            module_num=0,   # not used; LaTeX counter handles it
            q_num=q_num,
            q_text=q_text,
            analysis=analysis,
            images_dir=images_dir,
        ))

    return "\n".join(parts)


def generate_full_tex(
    modules_data: list[tuple[str, list[tuple[int, str, dict]]]],
    images_dir: str = "lab5img",
) -> str:
    """
    Generate a complete compilable LaTeX document.

    modules_data: list of (module_title, questions_analyses)
    questions_analyses: list of (q_num, q_text, analysis_dict)
    """
    parts: list[str] = [_PREAMBLE, _TITLEPAGE]

    for module_title, questions_analyses in modules_data:
        parts.append(render_module(module_title, questions_analyses, images_dir))

    parts.append(_END)
    return "\n".join(parts)
